config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import include, path

from config.views import Home

from snippetshero.views import LanguagesList, UserCreateView, UserDetail, UserLoginView, SnippetsByTag, UserUpdate, \
    ChangeUserPrivacy, ChangeUserPassword, SnippetsSearchView

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('snippets/', include('snippetshero.urls')),
    path('languages/', LanguagesList.as_view(), name='languages-list'),
    path('languages/<str:language>', LanguagesList.as_view(), name='language-snippets'),
    path('signup', UserCreateView.as_view(), name='user-create'),
    path('login', UserLoginView.as_view(), name='user-login'),
    path('logout', LogoutView.as_view(), name='user-logout'),
    path('snippetshero_user/<int:pk>', UserDetail.as_view(), name='user-detail'),
    path('snippetshero_user/<int:pk>/update', UserUpdate.as_view(), name='user-update'),
    path('snippetshero_user/<int:pk>/update-privacy', ChangeUserPrivacy.as_view(), name='user-update-privacy'),
    path('tags/<str:tag>', SnippetsByTag.as_view(), name='snippets-by-tag'),
    path('password_change/', ChangeUserPassword.as_view(), name='password_change'),
    path('search/', SnippetsSearchView.as_view(), name='search')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

snippetshero/urls.py
from django.urls import path
from snippetshero.views import SnippetDetail, SnippetCreate, SnippetUpdate, \
    SnippetLikeView, SnippetSaveView, SnippetDelete, SnippetRemoveTagView, CreateCommentView, CommentDelete, \
    CommentUpdate

app_name = 'snippetshero'

urlpatterns = [
    path('create', SnippetCreate.as_view(), name='snippet-create'),
    path('<int:pk>/detail', SnippetDetail.as_view(), name='snippet-detail'),
    path('<int:pk>/add-comment', CreateCommentView.as_view(), name='create-comment'),
    path('<int:pk>/comments/<int:comment>/update', CommentUpdate.as_view(), name='update-comment'),
    path('<int:pk>/comments/<int:comment>/delete', CommentDelete.as_view(), name='delete-comment'),
    path('<int:pk>/update', SnippetUpdate.as_view(), name='snippet-update'),
    path('<int:pk>/delete', SnippetDelete.as_view(), name='snippet-delete'),
    path('<int:pk>/like', SnippetLikeView.as_view(), name='snippet-like'),
    path('<int:pk>/save', SnippetSaveView.as_view(), name='snippet-save'),
    path('<int:pk>/tags/<str:tag_name>/remove', SnippetRemoveTagView.as_view(), name='tag-remove')
]

snippetshero/models.py
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.templatetags.static import static


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)


class Language(models.Model):
    title = models.CharField(max_length=30, unique=True)
    value = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        ordering = ['title']


class Snippet(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='snippets', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    language = models.ForeignKey(Language, on_delete=models.PROTECT)
    code = models.TextField()
    stars = models.IntegerField(default=0)
    tags = models.ManyToManyField(Tag, blank=True)
    create_on = models.DateTimeField(auto_now_add=True, editable=False)

    # class Meta:
    #    verbose_name_plural = 'Snippets'

    def __str__(self):
        return f"{self.title} - id: {self.id}"


class UserProfile(AbstractUser):
    first_name = models.CharField(_('first name'), max_length=150)
    last_name = models.CharField(_('last name'), max_length=150)
    email = models.EmailField(_('email address'), unique=True)
    saved = models.ManyToManyField(Snippet)
    liked = models.ManyToManyField(Snippet, related_name='likes')
    image = models.ImageField(upload_to='profile_images', null=True, blank=True, default=None)
    private = models.BooleanField(default=False)

    def get_profile_image(self):
        try:
            return self.image.url
        except ValueError:
            return static('img/user.svg')

    def get_ranking(self):
        snippets = Snippet.objects.filter(author_id=self.pk)
        return sum(snippet.stars for snippet in snippets)


class Comment(models.Model):
    snippet = models.ForeignKey(Snippet, on_delete=models.CASCADE)
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    content = models.TextField()
    create_on = models.DateTimeField(auto_now_add=True, editable=False)

snippetshero/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView, FormView
from snippetshero.forms import SnippetForm, UserCreateForm, UserLoginForm, UserUpdateForm, ChangePasswordForm, \
    SnippetsSearchForm, CommentForm
from snippetshero.models import Snippet, Language, UserProfile, Tag, Comment


class SnippetCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Snippet
    template_name = 'snippetshero/snippets/snippet_create.html'
    success_url = reverse_lazy('home')
    form_class = SnippetForm
    success_message = 'Snippet created successfully!'

    def form_valid(self, form):
        form.instance.author = self.request.user
        _ = super().form_valid(form)
        tag_string = self.request.POST.get('tags')
        if tag_string != '':
            tags = tag_string.split(',')
            for tag_name in tags:
                try:
                    tag = Tag.objects.create(name=tag_name)
                except IntegrityError:
                    tag = Tag.objects.get(name=tag_name)
                self.object.tags.add(tag)
        self.success_url = reverse_lazy('snippetshero:snippet-detail', kwargs={'pk': self.object.pk})
        return HttpResponseRedirect(self.get_success_url())


class SnippetUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Snippet
    template_name = 'snippetshero/snippets/snippet_update.html'
    form_class = SnippetForm
    success_message = 'Snippet updated successfully!'

    def get(self, request, *args, **kwargs):
        self.success_url = reverse_lazy('snippetshero:snippet-detail', kwargs={'pk': self.kwargs['pk']})
        if not self.permission_granted(request):
            return HttpResponseRedirect(self.success_url)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.success_url = reverse_lazy('snippetshero:snippet-detail', kwargs={'pk': self.kwargs['pk']})
        if not self.permission_granted(request):
            return HttpResponseRedirect(self.success_url)
        return super().post(request, *args, **kwargs)

    def permission_granted(self, request):
        snippet = Snippet.objects.get(pk=self.kwargs['pk'])
        if request.user.pk == snippet.author.pk:
            return True
        return False

    def form_valid(self, form):
        form.instance.author = self.request.user
        response = super().form_valid(form)
        tag_string = self.request.POST.get('tags')
        if tag_string != '':
            tags = tag_string.split(',')
            for tag_name in tags:
                try:
                    tag = Tag.objects.create(name=tag_name)
                except IntegrityError:
                    tag = Tag.objects.get(name=tag_name)
                self.object.tags.add(tag)
        return response


class SnippetDetail(DetailView):
    model = Snippet
    template_name = 'snippetshero/snippets/snippet_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm(action=reverse_lazy('snippetshero:create-comment', kwargs={'pk': self.kwargs['pk']}), submit_label='Add comment')
        return context


class SnippetDelete(LoginRequiredMixin, DeleteView):
    model = Snippet
    success_url = reverse_lazy('home')
    success_message = 'Snippet deleted successfully!'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse_lazy('snippetshero:snippet-detail', kwargs={'pk': self.kwargs['pk']}))


class LanguagesList(ListView):
    model = Language
    template_name = 'snippetshero/languages.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            language = Language.objects.get(value=self.kwargs['language'])
            context['snippets'] = Snippet.objects.filter(language=language)
            context['language'] = language
        except KeyError:
            pass
        return context


class UserCreateView(SuccessMessageMixin, CreateView):
    form_class = UserCreateForm
    template_name = 'snippetshero/registration/signup.html'
    success_url = reverse_lazy('home')
    success_message = "User created successfully!"


class UserLoginView(LoginView):
    form_class = UserLoginForm
    template_name = 'snippetshero/registration/login.html'
    success_url = reverse_lazy('home')


class SnippetLikeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse_lazy('snippetshero:snippet-detail', kwargs={'pk': self.kwargs['pk']}))

    def post(self, request, *args, **kwargs):
        snippet = Snippet.objects.get(pk=self.kwargs['pk'])
        if request.user.liked.filter(pk=snippet.pk).count() == 0:
            request.user.liked.add(snippet)
            snippet.stars += 1
        else:
            request.user.liked.remove(snippet)
            snippet.stars -= 1
        snippet.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class SnippetSaveView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse_lazy('snippetshero:snippet-detail', kwargs={'pk': self.kwargs['pk']}))

    def post(self, request, *args, **kwargs):
        snippet = Snippet.objects.get(pk=self.kwargs['pk'])
        if request.user.saved.filter(pk=snippet.pk).count() == 0:
            request.user.saved.add(snippet)
        else:
            request.user.saved.remove(snippet)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class UserDetail(DetailView):
    model = UserProfile
    template_name = 'snippetshero/snippetshero_user/user_detail.html'


class SnippetRemoveTagView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse_lazy('snippetshero:snippet-detail', kwargs={'pk': self.kwargs['pk']}))

    def post(self, request, *args, **kwargs):
        snippet = Snippet.objects.get(pk=self.kwargs['pk'])
        tag = Tag.objects.get(name=self.kwargs['tag_name'])
        snippet.tags.remove(tag)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class SnippetsByTag(ListView):
    model = Snippet
    template_name = 'snippetshero/snippets/snippets_by_tag.html'

    def get_queryset(self):
        tag_name = self.kwargs['tag']
        tag = Tag.objects.get(name=tag_name)
        snippets = tag.snippet_set.all()
        return snippets

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag_name'] = self.kwargs['tag']
        return context


class UserUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = UserProfile
    template_name = 'snippetshero/snippetshero_user/user_update.html'
    form_class = UserUpdateForm
    success_message = 'User updated successfully!'

    def get(self, request, *args, **kwargs):
        self.success_url = reverse_lazy('user-detail', kwargs={'pk': self.kwargs['pk']})
        if not self.permission_granted(request):
            return HttpResponseRedirect(self.success_url)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.success_url = reverse_lazy('user-detail', kwargs={'pk': self.kwargs['pk']})
        if not self.permission_granted(request):
            return HttpResponseRedirect(self.success_url)
        return super().post(request, *args, **kwargs)

    def permission_granted(self, request):
        user = UserProfile.objects.get(pk=self.kwargs['pk'])
        if request.user.pk == user.pk:
            return True
        return False


class ChangeUserPrivacy(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse_lazy('user-detail', kwargs={'pk': self.kwargs['pk']}))

    def post(self, request, *args, **kwargs):
        user = UserProfile.objects.get(pk=self.kwargs['pk'])
        if request.user.pk == user.pk:
            user.private = not user.private
        user.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ChangeUserPassword(SuccessMessageMixin, PasswordChangeView):
    form_class = ChangePasswordForm
    template_name = 'snippetshero/registration/password_change_form.html'
    success_message = 'Password changed successfully!'

    def post(self, request, *args, **kwargs):
        self.success_url = reverse_lazy('user-detail', kwargs={'pk': request.user.pk})
        return super().post(request, *args, **kwargs)


class SnippetsSearchView(FormView):
    model = Snippet
    template_name = 'snippetshero/search.html'
    form_class = SnippetsSearchForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        snippets = Snippet.objects.all()
        username = self.request.GET.get('username')
        min_date = self.request.GET.get('min_date')
        max_date = self.request.GET.get('max_date')
        language = self.request.GET.get('language')
        tags = self.request.GET.get('tags')
        params = [username, min_date, max_date, language, tags]
        if all(param in [None, ''] for param in params):
            return context
        if username not in [None, '']:

snippetshero/templates/snippetshero/snippets/popular_tags.html
<div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-4">
    <div class="col-auto flex-grow-1">
        <h3 class="mb-3">Popular Tags</h3>
    </div>

</div>
<div class="row row-cols-1 row-cols-lg-3 g-4">
    <div class="col-12">
        {% for tag in tags %}
            <a class="btn btn-warning my-1" href="{% url 'snippets-by-tag' tag.name %}" role="button">{{ tag.name }}</a>
        {% endfor %}
    </div>
</div>

snippetshero/templates/snippetshero/snippets/snippet_card.html
<div class="col">
    <div class="card h-100">
        <div class="card-body">
            <h5 class="card-title">{{ snippet.title }}</h5>
            <h6 class="card-subtitle">@{{ snippet.author.username }}</h6>
            <p class="card-text pt-3">{% if snippet.description == "" %}No description.{% else %}{{ snippet.description|truncatechars:100 }}{% endif %}</p>
        </div>
        <div class="ps-3 pb-3">
            <a class="btn btn-warning" href="{% url 'snippetshero:snippet-detail' snippet.pk %}" role="button">View snippet</a>
        </div>
        <div class="card-footer">
            <small class="text-muted">{{ snippet.language.title }} |
                <i class="bi bi-star-fill text-warning h6"></i>
                {{ snippet.stars }}</small>
        </div>
    </div>
</div>

snippetshero/templates/snippetshero/snippets/snippet_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}New snippet{% endblock %}

{% block head %}
    <link rel="stylesheet" href="https://rawcdn.githack.com/darkterminal/tagin/6fa2863c13aa1841f33cf6dcbbf266c92fbf5412/dist/css/tagin.min.css">
    <script src="https://rawcdn.githack.com/darkterminal/tagin/6fa2863c13aa1841f33cf6dcbbf266c92fbf5412/dist/js/tagin.min.js"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
            </div>
            <div class="col-15 py-4">
                <h1> New snippet</h1>
                {% crispy form %}
            </div>
            <div class="col">
            </div>
        </div>
    </div>
{% endblock %}

snippetshero/templates/snippetshero/snippets/snippet_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{ object.title }}{% endblock %}

{% block head %}
    <link href="{% static 'css/prism.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container my-4">
        <div class="container my-3">
            <div class="row align-items-center">
                <div class="col-auto px-0 me-3">
                    <img src="{{ object.author.get_profile_image }}" alt="usr" class="rounded-circle border border-3 border-dark" width="150" height="150" style="object-fit: cover;">
                </div>
                <div class="col-auto text-left flex-grow-1">
                    <h3 class="mb-3">@{{ object.author.username }}</h3>
                    <a class="btn btn-warning" href="{% url 'user-detail' object.author.pk %}" role="button">View profile</a>
                </div>
                {% if user.is_authenticated %}
                    <div class="col-auto px-0 py-3">
                        <form method="POST" action="{% url 'snippetshero:snippet-like' object.pk %}" class="mb-3 me-0">
                            {% csrf_token %}
                            <button type="submit" class="btn btn{% if not object in user.liked.all %}-outline{% endif %}-warning btn-block w-100">
                                {{ object.stars }}
                                <i class="bi bi-star"></i>
                            </button>
                        </form>

                        <form method="POST" action="{% url 'snippetshero:snippet-save' object.pk %}" class="mb-3 me-0">
                            {% csrf_token %}
                            {% if object in user.saved.all %}
                                <button type="submit" class="btn btn-warning btn-block w-100">
                                    Saved
                                    <i class="bi bi-bookmark"></i>
                                </button>
                            {% else %}
                                <button type="submit" class="btn btn-outline-warning btn-block w-100">
                                    Save
                                    <i class="bi bi-bookmark"></i>
                                </button>
                            {% endif %}

                        </form>

                        {% if object.author.pk == user.pk %}
                            <div class="btn-group me-0">
                                <button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    Options
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'snippetshero:snippet-update' object.pk %}">Edit</a></li>
                                    <li><a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deleteSnippet">Delete</a></li>
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
        <h3>{{ object.title }}</h3>
        <hr>
        <p>{% if object.description == "" %}No description.{% else %}{{ object.description|linebreaks }}{% endif %}</p>
        <h3>{{ object.language }}</h3>
        <hr>
        <pre class="my-3"><code class="language-{{ object.language.value }}">{{ object.code }}</code> </pre>
        <h3>Tags</h3>
        <hr>
        {% if object.author.pk == user.pk %}
            {% for tag in object.tags.all %}
                <form method="POST" action="{% url 'snippetshero:tag-remove' object.pk tag.name %}" class="mb-3 me-0 d-inline">
                    {% csrf_token %}
                    <div class="btn-group my-1" role="group">
                        <a class="btn btn-outline-dark" href="{% url 'snippets-by-tag' tag.name %}" role="button">{{ tag.name }}</a>
                        <button type="submit" class="btn btn-outline-dark px-2">
                            <i class="bi bi-x"></i>
                        </button>
                    </div>
                </form>
            {% endfor %}
        {% else %}
            {% for tag in object.tags.all %}
                <a class="btn btn-outline-dark" href="{% url 'snippets-by-tag' tag.name %}" role="button">{{ tag.name }}</a>
            {% endfor %}
        {% endif %}
        <h3 class="mt-3">Comments</h3>
        <hr>
        <div class="overflow-auto" style="max-height: 400px">
            <div class="list-group">
                {% for comment in object.comment_set.all %}
                    <div class="list-group-item">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">@{{ comment.author.username }}</h5>
                            <small>{{ comment.create_on|date:"d M Y P" }}</small>
                        </div>
                        <div class="d-flex w-100 justify-content-between">
                            <p class="mb-1">{{ comment.content}}</p>
                            {% if comment.author.pk == user.pk %}
                                <div class="btn-group me-0">
                                    <button type="button" class="btn" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-three-dots"></i>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="{% url 'snippetshero:update-comment' object.pk comment.pk %}">Edit</a></li>
                                        <li><a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deleteComment" data-bs-comment-delete="{% url 'snippetshero:delete-comment' object.pk comment.pk %}">Delete</a></li>
                                    </ul>
                                </div>
                            {% endif %}
                        </div>

                    </div>
                {% endfor %}
            </div>
        </div>
        {% if user.is_authenticated %}
            <hr>
            {% crispy form %}
        {% endif %}

    </div>

    <!-- Modal -->
    <div class="modal fade" id="deleteSnippet" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete snippet</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete snippet "{{ object.title }}"?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Cancel</button>
                    <form method="POST" action="{% url 'snippetshero:snippet-delete' object.pk %}">
                        {% csrf_token %}
                        <input type="submit" value="Delete" class="btn btn-warning">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteComment" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete comment</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete your comment?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Cancel</button>
                    <form method="POST" id="deleteCommentForm">
                        {% csrf_token %}
                        <input type="submit" value="Delete" class="btn btn-warning">
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block scripts %}
    <script src="{% static 'js/prism.js' %}"></script>
    <script src="{%  static 'js/delete_comment.js' %}"></script>
    <script src="{%  static 'js/update_comment.js' %}"></script>
{% endblock %}

snippetshero/templates/snippetshero/snippets/snippet_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Update snippet{% endblock %}

{% block head %}
    <link rel="stylesheet" href="https://rawcdn.githack.com/darkterminal/tagin/6fa2863c13aa1841f33cf6dcbbf266c92fbf5412/dist/css/tagin.min.css">
    <script src="https://rawcdn.githack.com/darkterminal/tagin/6fa2863c13aa1841f33cf6dcbbf266c92fbf5412/dist/js/tagin.min.js"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
            </div>
            <div class="col-15 py-4">
                <h1> Update snippet</h1>
                {% crispy form %}
            </div>
            <div class="col">
            </div>
        </div>
    </div>
{% endblock %}

snippetshero/templates/snippetshero/snippets/snippets_by_tag.html
{% extends 'base.html' %}

{% block title %}
    Tag: {{ tag_name }}
{% endblock %}

{% block content %}
    <div class="container my-3">
        <div class="row">
            <h1 class="">Tag: {{ tag_name }}</h1>
        </div>
        <hr>
        <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-4 my-3">
            {% for snippet in object_list %}
                {% include 'snippetshero/snippets/snippet_card.html' with snippet=snippet only %}
            {% endfor %}
        </div>
    </div>
{% endblock %} %}

snippetshero/templates/snippetshero/snippets/snippets_carousel.html
<div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-4">
    <div class="col-auto flex-grow-1">
        <h3 class="mb-3">{{ carousel_title }}</h3>
    </div>
    <div class="col-auto text-right">
        <button class="btn btn-warning mb-3 mr-1" type="button" data-bs-target="#{{ carousel_id }}" data-bs-slide="prev">
            <i class="bi bi-caret-left-fill"></i>
        </button>
        <button class="btn btn-warning mb-3" type="button" data-bs-target="#{{ carousel_id }}" data-bs-slide="next">
            <i class="bi bi-caret-right-fill"></i>
        </button>
    </div>
</div>
<div class="row row-cols-1 row-cols-lg-3 g-4">
    <div class="col-12">
        <div id="{{ carousel_id }}" class="carousel slide" data-bs-interval="false">
            <div class="carousel-inner">
                {% for snippet in snippets %}
                    {% if forloop.first %}
                        <div class="carousel-item active">
                        <div class="row row-cols-1 row-cols-lg-3 g-4 mb-3">
                    {% elif forloop.counter0|divisibleby:3 %}
                        <div class="carousel-item">
                        <div class="row row-cols-1 row-cols-lg-3 g-4 mb-3">
                    {% endif %}
                {% include 'snippetshero/snippets/snippet_card.html' with snippet=snippet only %}
                {% if forloop.counter|divisibleby:3 or forloop.last %}
                    </div></div>
                {% endif %}
                {% endfor %}

                </div>
                </div>
            </div>
        </div>