config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import include, path

from config.views import Home

from snippetshero.views import LanguagesList, UserCreateView, UserDetail, UserLoginView, SnippetsByTag, UserUpdate, \
    ChangeUserPrivacy, ChangeUserPassword, SnippetsSearchView

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('snippets/', include('snippetshero.urls')),
    path('languages/', LanguagesList.as_view(), name='languages-list'),
    path('languages/<str:language>', LanguagesList.as_view(), name='language-snippets'),
    path('signup', UserCreateView.as_view(), name='user-create'),
    path('login', UserLoginView.as_view(), name='user-login'),
    path('logout', LogoutView.as_view(), name='user-logout'),
    path('snippetshero_user/<int:pk>', UserDetail.as_view(), name='user-detail'),
    path('snippetshero_user/<int:pk>/update', UserUpdate.as_view(), name='user-update'),
    path('snippetshero_user/<int:pk>/update-privacy', ChangeUserPrivacy.as_view(), name='user-update-privacy'),
    path('tags/<str:tag>', SnippetsByTag.as_view(), name='snippets-by-tag'),
    path('password_change/', ChangeUserPassword.as_view(), name='password_change'),
    path('search/', SnippetsSearchView.as_view(), name='search')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

snippetshero/urls.py
from django.urls import path
from snippetshero.views import SnippetDetail, SnippetCreate, SnippetUpdate, \
    SnippetLikeView, SnippetSaveView, SnippetDelete, SnippetRemoveTagView, CreateCommentView, CommentDelete, \
    CommentUpdate

app_name = 'snippetshero'

urlpatterns = [
    path('create', SnippetCreate.as_view(), name='snippet-create'),
    path('<int:pk>/detail', SnippetDetail.as_view(), name='snippet-detail'),
    path('<int:pk>/add-comment', CreateCommentView.as_view(), name='create-comment'),
    path('<int:pk>/comments/<int:comment>/update', CommentUpdate.as_view(), name='update-comment'),
    path('<int:pk>/comments/<int:comment>/delete', CommentDelete.as_view(), name='delete-comment'),
    path('<int:pk>/update', SnippetUpdate.as_view(), name='snippet-update'),
    path('<int:pk>/delete', SnippetDelete.as_view(), name='snippet-delete'),
    path('<int:pk>/like', SnippetLikeView.as_view(), name='snippet-like'),
    path('<int:pk>/save', SnippetSaveView.as_view(), name='snippet-save'),
    path('<int:pk>/tags/<str:tag_name>/remove', SnippetRemoveTagView.as_view(), name='tag-remove')
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <script src="{% static 'js/custom.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
    {% block head %}

    {% endblock %}
</head>
{% block body %}
    <body>

    <header class="p-3 bg-dark text-white">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="{% url 'home' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <img src="{% static 'img/SnippetsHeroLogo.svg' %}" width="50" height="50" alt="Logo">
                </a>

                {% with request.resolver_match.url_name as url_name %}
                    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 px-3">
                        <li><a href="{% url 'home' %}" class="nav-link px-2 {% if url_name == 'home' %} text-warning {% else %} text-secondary {% endif %}">Home</a></li>
                        <li><a href="{% url 'languages-list' %}" class="nav-link px-2 {% if url_name == 'languages-list' or url_name == 'language-snippets' %} text-warning {% else %} text-secondary {% endif %}">Languages</a></li>
                        <li><a href="{% url 'search' %}" class="nav-link px-2 {% if url_name == 'search' %} text-warning {% else %} text-secondary {% endif %}">Search</a></li>
                    </ul>
                {% endwith %}




                {% if user.is_authenticated %}
                    <div class="dropdown text-end">
                        <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.get_profile_image }}" alt="usr" class="rounded-circle" width="50" height="50" style="object-fit: cover;">
                        </a>
                        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
                            <li><a class="dropdown-item" href="{% url 'snippetshero:snippet-create' %}">New snippet...</a></li>
                            <li><a class="dropdown-item" href="{% url 'user-detail' user.pk %}">Profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'user-logout' %}">Sign out</a></li>
                        </ul>
                    </div>
                {% else %}
                    <div class="text-end">
                        <a class="btn btn-outline-light me-2" href="{% url 'user-login' %}" role="button">Login</a>
                        <a class="btn btn-warning" href="{% url 'user-create' %}" role="button">Sign-up</a>
                    </div>
                {% endif %}


            </div>
        </div>
    </header>

    <div class="container">
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show my-4" role="alert">
                {{ message | safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>


    {% block content %}

    {% endblock %}

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    {% block scripts %}

    {% endblock %}
    </body>
{% endblock %}

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block head %}
    {#    <script type='text/javascript' src='https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js'></script>#}
{% endblock %}

{% block content %}

    <div class="container my-3">
        {% if not user.is_authenticated %}
            <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
                <div class="col-10 col-sm-8 col-lg-6">
                    <img src="{% static 'img/SnippetsHero.svg' %}" class="d-block mx-lg-auto img-fluid" alt="SnippetsHero" width="500" height="500">
                </div>
                <div class="col-lg-6">
                    <h1 class="lh-1 mb-3">Welcome to Snippets Hero!</h1>
                    <p class="fs-4">Snippets Hero is a platform that allows you to share snippets with other users.
                        The main goal is to support open-source code and help developers find solutions to their problems.
                    </p>


                    <p class="lead fs-4 d-inline">Are you ready to become the next</p>
                    <p class="fs-4 d-inline">Snippets Hero</p><p class="lead fs-4 d-inline">?</p>
                    <br><br>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a class="btn btn-outline-dark btn-lg px-4" href="{% url 'user-login' %}" role="button">Login</a>
                        <a class="btn btn-warning btn-lg px-4 me-md-2" href="{% url 'user-create' %}" role="button">Sign-up</a>
                    </div>


                </div>
            </div>
        {% else %}
            <div class="row align-items-center">
                <div class="col-auto flex-grow-1">
                    <h1>Hi, {{ user.first_name }}!</h1>
                </div>
                <div class="col-auto">
                    <a class="btn btn-warning" href="{% url 'snippetshero:snippet-create' %}" role="button">New snippet</a>
                </div>
            </div>
        {% endif %}
        <hr>
        {% include 'snippetshero/snippetshero_user/snippets_heroes_carousel.html' with carousel_title='Hall of Fame' carousel_id='snippetsHeroesCarousel' snippets_heroes=snippets_heroes %}
        <hr class="my-3">
        {% include 'snippetshero/snippets/snippets_carousel.html' with carousel_title='Top Snippets' carousel_id='topSnippetsCarousel' snippets=top_snippets %}
        <hr class="my-3">
        {% include 'snippetshero/snippets/snippets_carousel.html' with carousel_title='Recent Snippets' carousel_id='recentSnippetsCarousel' snippets=recent_snippets %}
        <hr class="my-3">
        {% include 'snippetshero/snippets/popular_tags.html' with tags=popular_tags %}
    </div>

{% endblock %}